export const SINGAPORE_SUBREGIONS = [
    { id: 1, name: "Ang Mo Kio" }, { id: 2, name: "Bedok" }, { id: 3, name: "Bishan" },
    { id: 4, name: "Bukit Batok" }, { id: 5, name: "Bukit Merah" }, { id: 6, name: "Bukit Panjang" },
    { id: 7, name: "Bukit Timah" }, { id: 8, name: "Central Water Catchment" }, { id: 9, name: "Changi" },
    { id: 10, name: "Changi Bay" }, { id: 11, name: "Choa Chu Kang" }, { id: 12, name: "Clementi" },
    { id: 13, name: "Downtown Core" }, { id: 14, name: "Geylang" }, { id: 15, name: "Hougang" },
    { id: 16, name: "Jurong East" }, { id: 17, name: "Jurong West" }, { id: 18, name: "Kallang" },
    { id: 19, name: "Lim Chu Kang" }, { id: 20, name: "Mandai" }, { id: 21, name: "Marina East" },
    { id: 22, name: "Marina South" }, { id: 23, name: "Marine Parade" }, { id: 24, name: "Museum" },
    { id: 25, name: "Newton" }, { id: 26, name: "North-Eastern Islands" }, { id: 27, name: "Novena" },
    { id: 28, name: "Orchard" }, { id: 29, name: "Outram" }, { id: 30, name: "Pasir Ris" },
    { id: 31, name: "Paya Lebar" }, { id: 32, name: "Pioneer" }, { id: 33, name: "Punggol" },
    { id: 34, name: "Queenstown" }, { id: 35, name: "River Valley" }, { id: 36, name: "Rochor" },
    { id: 37, name: "Seletar" }, { id: 38, name: "Sembawang" }, { id: 39, name: "Sengkang" },
    { id: 40, name: "Serangoon" }, { id: 41, name: "Simpang" }, { id: 42, name: "Singapore River" },
    { id: 43, name: "Southern Islands" }, { id: 44, name: "Straits View" }, { id: 45, name: "Sungei Kadut" },
    { id: 46, name: "Tampines" }, { id: 47, name: "Tanglin" }, { id: 48, name: "Tengah" },
    { id: 49, name: "Toa Payoh" }, { id: 50, name: "Tuas" }, { id: 51, name: "Western Islands" },
    { id: 52, name: "Western Water Catchment" }, { id: 53, name: "Woodlands" }, { id: 54, name: "Yishun" },
    { id: 55, name: "Tiong Bahru" }, { id: 56, name: "Chinatown" }, { id: 57, name: "Little India" },
    { id: 58, name: "Kovan" }, { id: 59, name: "Potong Pasir" }, { id: 60, name: "Mountbatten" },
    { id: 61, name: "Joo Chiat" }, { id: 62, name: "Siglap" }, { id: 63, name: "Katong" },
    { id: 64, name: "Aljunied" }, { id: 65, name: "Eunos" }, { id: 66, name: "Tai Seng" },
    { id: 67, name: "MacPherson" }, { id: 68, name: "Whampoa" }, { id: 69, name: "Balestier" },
    { id: 70, name: "Boon Keng" }, { id: 71, name: "Bendemeer" }, { id: 72, name: "Farrer Park" },
    { id: 73, name: "Bugis" }, { id: 74, name: "Clarke Quay" }, { id: 75, name: "Robertson Quay" },
    { id: 76, name: "Tanjong Pagar" }, { id: 77, name: "Telok Ayer" }, { id: 78, name: "Raffles Place" },
    { id: 79, name: "Shenton Way" }, { id: 80, name: "Marina Bay" }, { id: 81, name: "Sentosa" },
    { id: 82, name: "HarbourFront" }, { id: 83, name: "Telok Blangah" }, { id: 84, name: "Pasir Panjang" },
    { id: 85, name: "Kent Ridge" }
];
