import { normalizeRole } from './roles.js';

export function formatHardAssetListSummary(asset, options = {}) {
    const membershipSummary = options.membershipSummary || {};
    const partnerRole = asset?.partner?.role ? normalizeRole(asset.partner.role) : null;

    return {
        id: asset.id,
        editSummary: true,
        externalKey: asset.externalKey || null,
        name: asset.name,
        country: asset.country || 'SG',
        address: asset.address,
        postalCode: asset.postalCode,
        subregionId: asset.subregionId || null,
        subCategory: asset.subCategory,
        phone: asset.phone || null,
        whatsappContact: asset.whatsappContact || null,
        contactEmail: asset.contactEmail || null,
        hours: asset.hours || null,
        website: asset.website || null,
        socialLinks: asset.socialLinks || {},
        description: asset.description || null,
        logoUrl: asset.logoUrl || null,
        bannerUrl: asset.bannerUrl || null,
        galleryUrls: Array.isArray(asset.galleryUrls) ? asset.galleryUrls : [],
        sourceGooglePlaceId: asset.sourceGooglePlaceId || null,
        sourceGoogleMapsUri: asset.sourceGoogleMapsUri || null,
        isHidden: asset.isHidden || false,
        hideFrom: asset.hideFrom || null,
        hideUntil: asset.hideUntil || null,
        updatedAt: asset.updatedAt || null,
        creatorName: asset.creator?.name || null,
        updatedByName: asset.updater?.name || asset.creator?.name || null,
        lastReviewedAt: asset.lastReviewedAt || null,
        lastVerifiedByUserId: asset.lastVerifiedByUserId || null,
        sourceType: asset.sourceType || null,
        verificationStatus: asset.verificationStatus || 'unverified',
        verificationConfidence: asset.verificationConfidence || null,
        partnerId: asset.partnerId || null,
        partnerName: asset.partner?.name || null,
        partnerRole,
        ownershipMode: asset.partnerId ? 'partner' : 'system',
        tags: Array.isArray(options.tags) ? options.tags : [],
        boundaryStatus: options.boundaryStatus || 'no-boundary',
        matchingRegionIds: Array.isArray(asset.matchingRegionIds) ? asset.matchingRegionIds : [],
        primaryRegionId: asset.subregionId || null,
        organizationLinks: Array.isArray(options.organizationLinks) ? options.organizationLinks : [],
        permissions: options.permissions || {
            canEdit: false,
            canManageAccess: false,
            canDelete: false,
            canHide: false,
        },
        ...membershipSummary,
    };
}
