import test from 'node:test';
import assert from 'node:assert/strict';

import { formatSoftAssetListSummary } from '../src/utils/softAssetListSummary.js';

test('soft asset list summaries keep dashboard fields and omit heavy nested payloads', () => {
    const summary = formatSoftAssetListSummary({
        id: 44,
        externalKey: 'offering-example',
        partnerId: 5,
        subregionId: 9,
        assetMode: 'child',
        parentSoftAssetId: 12,
        hostHardAssetId: 99,
        name: 'Example Exercise Class',
        bucket: 'activity',
        subCategory: 'Exercise',
        description: 'Light exercise for seniors.',
        schedule: 'Mondays',
        logoUrl: 'https://example.test/logo.png',
        bannerUrl: 'https://example.test/banner.png',
        galleryUrls: ['https://example.test/gallery.png'],
        audienceMode: 'audience_zones',
        isMemberOnly: true,
        eligibilityRules: { minAge: 65 },
        overriddenFields: ['contactPhone'],
        contactPhone: '6000 0000',
        contactEmail: 'hello@example.test',
        availabilityEnabled: true,
        availabilityCount: 3,
        availabilityUnit: 'slots',
        isHidden: false,
        partner: { id: 5, name: 'Legacy Owner', role: 'partner' },
        parent: {
            id: 12,
            name: 'Parent Template',
            audienceZones: [
                { audienceZone: { id: 8, name: 'Zone A', zoneCode: 'ZA', partnerUserId: 5 } },
            ],
        },
        hostHardAsset: {
            id: 99,
            name: 'Host Place',
            address: 'Blk 1 Example Road',
            country: 'SG',
            postalCode: '123456',
            subregionId: 9,
            subCategory: 'Active Ageing Centre (AAC)',
            logoUrl: 'https://example.test/host.png',
            matchingRegionIds: [9],
            partner: { id: 7, name: 'Host Owner', role: 'partner' },
        },
        tags: [{ tag: { name: 'Fitness' } }],
        audienceZones: [],
        translations: { zh: { name: 'Translated' } },
        locations: [{ hardAsset: { id: 100, name: 'Extra heavy linked place' } }],
    }, {
        boundaryStatus: 'inside',
        organizationLinks: [{ organizationId: 3, organizationName: 'Pilot Org' }],
        permissions: {
            canEdit: true,
            canManageAccess: false,
            canDelete: true,
            canHide: true,
        },
    });

    assert.deepEqual(summary, {
        id: 44,
        externalKey: 'offering-example',
        partnerId: 5,
        subregionId: 9,
        assetMode: 'child',
        parentSoftAssetId: 12,
        hostHardAssetId: 99,
        name: 'Example Exercise Class',
        bucket: 'activity',
        subCategory: 'Exercise',
        description: 'Light exercise for seniors.',
        schedule: 'Mondays',
        logoUrl: 'https://example.test/logo.png',
        bannerUrl: 'https://example.test/banner.png',
        audienceMode: 'audience_zones',
        isMemberOnly: true,
        overriddenFields: ['contactPhone'],
        contactPhone: '6000 0000',
        whatsappContact: null,
        contactEmail: 'hello@example.test',
        ctaLabel: null,
        ctaUrl: null,
        venueNote: null,
        availabilityEnabled: true,
        availabilityCount: 3,
        availabilityUnit: 'slots',
        lastReviewedAt: null,
        lastVerifiedByUserId: null,
        sourceType: null,
        verificationStatus: 'unverified',
        verificationConfidence: null,
        isHidden: false,
        hideFrom: null,
        hideUntil: null,
        updatedAt: null,
        partnerName: 'Legacy Owner',
        partnerRole: 'partner',
        ownershipMode: 'partner',
        tags: ['Fitness'],
        audienceZones: [{ id: 8, name: 'Zone A', zoneCode: 'ZA', partnerUserId: 5 }],
        audienceZoneIds: [8],
        parentSummary: { id: 12, name: 'Parent Template' },
        locations: [{
            id: 99,
            name: 'Host Place',
            address: 'Blk 1 Example Road',
            country: 'SG',
            postalCode: '123456',
            subregionId: 9,
            subCategory: 'Active Ageing Centre (AAC)',
            logoUrl: 'https://example.test/host.png',
            partnerId: null,
            partnerName: 'Host Owner',
            partnerRole: 'partner',
            matchingRegionIds: [9],
        }],
        location: {
            id: 99,
            name: 'Host Place',
            address: 'Blk 1 Example Road',
            country: 'SG',
            postalCode: '123456',
            subregionId: 9,
            subCategory: 'Active Ageing Centre (AAC)',
            logoUrl: 'https://example.test/host.png',
            partnerId: null,
            partnerName: 'Host Owner',
            partnerRole: 'partner',
            matchingRegionIds: [9],
        },
        hostLocation: {
            id: 99,
            name: 'Host Place',
            address: 'Blk 1 Example Road',
            country: 'SG',
            postalCode: '123456',
            subregionId: 9,
            subCategory: 'Active Ageing Centre (AAC)',
            logoUrl: 'https://example.test/host.png',
            partnerId: null,
            partnerName: 'Host Owner',
            partnerRole: 'partner',
            matchingRegionIds: [9],
        },
        coverageRegionIds: [],
        matchingRegionIds: [],
        primaryRegionId: 9,
        boundaryStatus: 'inside',
        organizationLinks: [{ organizationId: 3, organizationName: 'Pilot Org' }],
        permissions: {
            canEdit: true,
            canManageAccess: false,
            canDelete: true,
            canHide: true,
        },
    });

    assert.equal(Object.hasOwn(summary, 'galleryUrls'), false);
    assert.equal(Object.hasOwn(summary, 'eligibilityRules'), false);
    assert.equal(Object.hasOwn(summary, 'translations'), false);
});
